import "./globals.css";
import Header from "@/components/Header/Header";


export const metadata = {
  title: "Sunrice Adventure In Magbay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className="bg-blueSunrise font-poppins">
        <Header/>
        <main className="flex flex-col -mt-[92px] h-full min-h-screen max-sm:-mt-[116px]">
                {children}
        </main>
      </body>

    </html>
  );
}