import "../globals.css"
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";




export const metadata = {
  title: "Sunrise Adventure In Magbay",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">

//       <body className="bg-blueSunrise font-poppins">
//         <Header/>
//         <main className="flex flex-col -mt-[92px] h-full min-h-screen max-sm:-mt-[116px]">
//                 {children}
//         </main>
//         <Footer/>
//       </body>

//     </html>
//   );
// }

export default async function RootLayout({ children, params }) {
  // Asegurar que el locale es válido
  
  const { locale } = await params;
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  // Obtener los mensajes de traducción
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className='bg-blueSunrise font-poppins'>
        <NextIntlClientProvider messages={messages}>
        <Header/>
        <main className="flex flex-col -mt-[92px] h-full min-h-screen max-sm:-mt-[116px]">
                {children}
        </main>
        <Footer/>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
